### ISSUE TITLE
White address bar, context menus

### ISSUE THREAD

**Issue by iAmMrinal0** [bbrks/chrome-gruvbox#1]
Hi, firstly, love the theme. Thanks for making it for Chrome. I just had a question, do you have plans to make the address bar and the context menus also as dark?

**Comment by bbrks** [comment]
Hi @iAmMrinal0,

Thanks for using and leaving a comment! Unfortunately Chrome does not allow you to style the address bar or context menus. Those colours are pulled from your operating system.

I think you can apply registry edits to change the address bar colour in Windows, but I have not tested this.

https://www.reddit.com/r/chrome/comments/3vstm5/i_made_a_material_dark_theme_for_chrome_thoughts/cxr1baa/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=chrome

> Only Way to do that is this..As far as I know certain aspects are changeable via Chrome Themes, but others, like the address bar, it's colours are pulled from your Windows settings.
Unfortunately starting with Windows 8 Microsoft got rid of (as far as I can tell) the "**Advanced Appearance Settings**" option from the "Personalization | Color" section when using most themes, however there are 2 options: via a High Contrast theme, or via a registry hack (the easiest way imo). Easy way first:
**Registry Hack**: If this is a tablet, swipe in from the right, and do a search for regedit. If you have a keyboard just hit Windows key + R, type in and run regedit. The section you want is under "HKEY_CURRENT_USER\Control Panel\Colors", and the option to change is "Window". These are all in RGB number values, so you need to find the value of the colour you want to use. So, 0 0 0 would be black (again, change your text colour first to something other than white until after you've changed the background to black) while 255 255 255 is white. I would suggest trying 128 128 128 or 192 192 192 which would give you either dark or light grey respectfully. Just remember that technically you are changing the value for window backgrounds, so that might include the Windows address bar too (it does this on Windows 7 for almost all address bars, but what it affects in Windows 8 varies.. it does it on some bars, but not on others like the main address bar for My Computer). After that just reboot the machine.
**High Contrast Theme**: Go to your desktop, swipe in from the right, choose Settings, then Personalization. From there choose a "High Contrast" theme, go into "Color", and you should be able to change the "Window Background" option. The address bar is considered a Window, so changing this colour will change that background, however the problem is that this will change ALL window backgrounds. Black text with white background should work, or just change the background to grey.

**Comment by iAmMrinal0** [comment]
Ah thanks. :+1:
